### ISSUE TITLE
cluster created but ingress failed 

### ISSUE THREAD

**Issue by elaubsch** [vanvalenlab/kiosk-console#195] opened 2019-12-21 02:27 UTC
tried to create a cluster and needed to enable Kubernetes API, did that via a link
retried to deploy a cluster and got this error

```
make[1]: *** No rule to make target 'Makefile.*'.  Stop.
Creating GKE service account...
ERROR: (gcloud.iam.service-accounts.create) Resource in project [shaped-kite-262700] is the subject of a conflict: Service account deepcell already exists within project projects/shaped-kite-262700.
- '@type': type.googleapis.com/google.rpc.ResourceInfo
  resourceName: projects/shaped-kite-262700/serviceAccounts/deepcell@shaped-kite-262700.iam.gserviceaccount.com
No need to create service account; it probably already exists.
Updated IAM policy for project [shaped-kite-262700].
bindings:
- members:
  - serviceAccount:service-764184534775@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-764184534775@container-engine-robot.iam.gserviceaccount.com
  role: roles/container.serviceAgent
- members:
  - serviceAccount:764184534775-compute@developer.gserviceaccount.com
  - serviceAccount:764184534775@cloudservices.gserviceaccount.com
  - serviceAccount:service-764184534775@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:lobster.emily@gmail.com
  role: roles/owner
- members:
  - serviceAccount:deepcell@shaped-kite-262700.iam.gserviceaccount.com
  role: roles/storage.admin
etag: BwWaLUwWxdE=
version: 1
GKE service account creation complete.
 
 
Creating GKE cluster...
Using the following command: 
gcloud container clusters create deepcell \
	--service-account=deepcell@shaped-kite-262700.iam.gserviceaccount.com \
	--region=us-west1 \
	--node-locations=us-west1-b,us-west1-a \
	--max-nodes=60 \
	--min-nodes=1 \
	--machine-type=n1-standard-1 \
	--cluster-version latest \
	--enable-autoscaling \
	--no-enable-autoupgrade \
	|| echo "Apparently, the cluster already exists."
WARNING: In June 2019, node auto-upgrade will be enabled by default for newly created clusters and node pools. To disable it, use the `--no-enable-autoupgrade` flag.
WARNING: Starting in 1.12, new clusters will have basic authentication disabled by default. Basic authentication can be enabled (or disabled) manually using the `--[no-]enable-basic-auth` flag.
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-certificate` flag.
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Creating cluster deepcell in us-west1...
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
Created [https://container.googleapis.com/v1/projects/shaped-kite-262700/zones/us-west1/clusters/deepcell].
To inspect the contents of your cluster, go to: https://console.cloud.google.com/kubernetes/workload_/gcloud/us-west1/deepcell?project=shaped-kite-262700
kubeconfig entry generated for deepcell.
NAME      LOCATION  MASTER_VERSION  MASTER_IP      MACHINE_TYPE   NODE_VERSION   NUM_NODES  STATUS
deepcell  us-west1  1.15.4-gke.22   35.247.116.69  n1-standard-1  1.15.4-gke.22  6          RUNNING
GKE cluster creation complete.
 
 
Creating consumer CPU node pool...
Using the following command: 
gcloud container node-pools create consumer-cpu \
	--cluster deepcell \
	--service-account=deepcell@shaped-kite-262700.iam.gserviceaccount.com \
	--region us-west1 \
	--num-nodes 1 \
	--min-nodes 1 \
	--max-nodes 60 \
	--machine-type=n1-highmem-2 \
	--enable-autoscaling \
	--enable-autorepair \
	--no-enable-autoupgrade \
	--preemptible \
	--node-labels consumer=yes \
	--node-taints consumer=yes:NoSchedule \
	|| echo "Elasticsearch CPU node pool creation failed."
WARNING: In June 2019, node auto-upgrade will be enabled by default for newly created clusters and node pools. To disable it, use the `--no-enable-autoupgrade` flag.
WARNING: Starting in 1.12, new node pools will be created with their legacy Compute Engine instance metadata APIs disabled by default. To create a node pool with legacy instance metadata endpoints disabled, run `node-pools create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Creating node pool consumer-cpu...
.......................................................................................................................................................................................................................................................................................done.
Created [https://container.googleapis.com/v1/projects/shaped-kite-262700/zones/us-west1/clusters/deepcell/nodePools/consumer-cpu].
NAME          MACHINE_TYPE  DISK_SIZE_GB  NODE_VERSION
consumer-cpu  n1-highmem-2  100           1.15.4-gke.22
Creating prediction GPU node pool...
Using the following command: 
gcloud container node-pools create prediction-gpu \
	--cluster deepcell \
	--accelerator type=nvidia-tesla-t4,count=1 \
	--service-account=deepcell@shaped-kite-262700.iam.gserviceaccount.com \
	--region us-west1 \
	--num-nodes 0 \
	--min-nodes 0 \
	--max-nodes 4 \
	--machine-type=n1-highmem-2 \
	--enable-autoscaling \
	--enable-autorepair \
	--no-enable-autoupgrade \
	--preemptible \
	--node-taints prediction_gpu=yes:NoSchedule \
	|| echo "Prediction GPU node pool creation failed."
WARNING: In June 2019, node auto-upgrade will be enabled by default for newly created clusters and node pools. To disable it, use the `--no-enable-autoupgrade` flag.
WARNING: Starting in 1.12, new node pools will be created with their legacy Compute Engine instance metadata APIs disabled by default. To create a node pool with legacy instance metadata endpoints disabled, run `node-pools create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Machines with GPUs have certain limitations which may affect your workflow. Learn more at https://cloud.google.com/kubernetes-engine/docs/how-to/gpus
Creating node pool prediction-gpu...
......................................................................................................done.
Created [https://container.googleapis.com/v1/projects/shaped-kite-262700/zones/us-west1/clusters/deepcell/nodePools/prediction-gpu].
NAME            MACHINE_TYPE  DISK_SIZE_GB  NODE_VERSION
prediction-gpu  n1-highmem-2  100           1.15.4-gke.22
Creating training GPU node pool...
Using the following command: 
gcloud container node-pools create training-gpu \
	--cluster deepcell \
	--accelerator type=nvidia-tesla-v100,count=1 \
	--service-account=deepcell@shaped-kite-262700.iam.gserviceaccount.com \
	--region us-west1 \
	--num-nodes 0 \
	--min-nodes 0 \
	--max-nodes 4 \
	--machine-type=n1-highmem-2 \
	--enable-autoscaling \
	--enable-autorepair \
	--no-enable-autoupgrade \
	--node-taints training_gpu=yes:NoSchedule \
	|| echo "Training GPU node pool creation failed."
WARNING: In June 2019, node auto-upgrade will be enabled by default for newly created clusters and node pools. To disable it, use the `--no-enable-autoupgrade` flag.
WARNING: Starting in 1.12, new node pools will be created with their legacy Compute Engine instance metadata APIs disabled by default. To create a node pool with legacy instance metadata endpoints disabled, run `node-pools create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Machines with GPUs have certain limitations which may affect your workflow. Learn more at https://cloud.google.com/kubernetes-engine/docs/how-to/gpus
Creating node pool training-gpu...
.......................................................................................................done.
Created [https://container.googleapis.com/v1/projects/shaped-kite-262700/zones/us-west1/clusters/deepcell/nodePools/training-gpu].
NAME          MACHINE_TYPE  DISK_SIZE_GB  NODE_VERSION
training-gpu  n1-highmem-2  100           1.15.4-gke.22
GPU node pool creation finished.
 
 
Creating Google Cloud Storage Bucket shaped-kite-262700...
Creating gs://20191220-bucket/...
ServiceException: 409 Bucket 20191220-bucket already exists.
Bucket  already exists. No need to create that bucket.
No changes to gs://20191220-bucket/
Google Cloud Storage Bucket creation finished.
 
 
Deploying kubernetes resources...
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-rule created
$HELM_HOME has been configured at /var/lib/helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
Kubernetes resource deployment finished.
 
 
Deploying NVIDIA drivers for GPU instances...
daemonset.apps/nvidia-driver-installer created
NVIDIA GPU driver deployment finished.
 
 
GKE cluster created
 
Syncing all Kubernetes resources using helmfiles...
/conf/patches/gke-helmfile-deployment.sh
/conf/helmfile.d/0000.ingress.yaml
ingress
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "cloudposse-incubator" chart repository
...Successfully got an update from the "coreos-stable" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

Upgrading stable/nginx-ingress
Release "ingress" does not exist. Installing it now.
Error: release ingress failed: services "ingress-nginx-ingress-controller-metrics" not found

err: release "ingress" in "0000.ingress.yaml" failed: exit status 1
exit status 1
Error: release: "ingress" not found
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "cloudposse-incubator" chart repository
...Successfully got an update from the "coreos-stable" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

Upgrading stable/nginx-ingress
UPGRADE FAILED
ROLLING BACK
Error: "ingress" has no deployed releases
Error: UPGRADE FAILED: "ingress" has no deployed releases

err: release "ingress" in "0000.ingress.yaml" failed: exit status 1
exit status 1
Error: release: "ingress" not found
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "cloudposse-incubator" chart repository
...Successfully got an update from the "coreos-stable" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

Upgrading stable/nginx-ingress
UPGRADE FAILED
ROLLING BACK
Error: "ingress" has no deployed releases
Error: UPGRADE FAILED: "ingress" has no deployed releases

err: release "ingress" in "0000.ingress.yaml" failed: exit status 1
```

**Comment by willgraf** [comment] 2020-12-09 06:28
This looks like it is related to #156 due to the `Error: release ingress failed: services "ingress-nginx-ingress-controller-metrics" not found` line.  The root cause is a problem hitting the GCP resource limits.

This issue will be closed as the root cause was resolved by #162. If this comes up again, this issue can be reopened.

**Closed by willgraf** 2020-12-09 06:28 UTC
Labels: bug
